### ISSUE TITLE
UIBarButtonItem helper function

### ISSUE THREAD

**Issue by teamdisc** [jjaaxx44/SurveyExample#3]
Hi Abhishek!

First of all, thank you for the assignment! I'm Team, one of the iOS developers in Nimble. I'm here to give my feedback upon your assignment. Feel free to disagree and provide any technical insight that I might be missing ✌🏻 Let's hope we can learn something new together!

Alright, let's get into it.

I'm not quite sure that maybe there could be a reason behind `UIBarButtonItem` extension, but can we use UIKit function of `UIBarButtonItem(image:style:target:selector)` directly? So in that case, we might not need to use `customView` or the extension 🤔

**Comment by jjaaxx44** [comment]
Hi Team,

Thats right, I had 100x100 icon and with default method, buttons were not looking good to my eyes.
So I made small extension rather than resizing (my home Mac is pretty slow).

Later on I ended up resizing images but for got fall back to default function.

I hope this makes sense...
