### ISSUE TITLE
No test coverage on the main use case

### ISSUE THREAD

**Issue by teamdisc** [jjaaxx44/SurveyExample#4]
It seems to me that the test cases implemented in the project might not cover the main use case of the app. For instance, after fetched the first page, when fetching the next page, on **Take Survey** button selected, or something like that. 

In `APITests`, I think that performing actual API requests in unit test will make it more of an integration test, rather than unit tests. And perhaps it could get flaky as waiting 5 seconds might not be the case every time. Especially with CI integrated in the project.

**Comment by jjaaxx44** [comment]
> For instance, after fetched the first page, when fetching the next page, on Take Survey button selected

Right I thought I was missing something :) should write cases later today and push?

> In APITests, I think that performing actual API requests in unit test will make it more of an integration test 

Yes I agree.

**Comment by jjaaxx44** [comment]
Hi Team,

I have added few more test cases, that you might check. Also we can add even more test cases, i.e. we can test expiration of auth by providing hardcoded json (wrong json, auth failed, expired etc).

-Abhishek
