### ISSUE TITLE
When the request finishes while users are scrolling

### ISSUE THREAD

**Issue by teamdisc** [jjaaxx44/SurveyExample#5]
I found out an issue, when fetching for the next/previous page and the request finishes while we're scrolling, there'll only be 2 pages available and the page control will no longer be in sync. 🤔

**Comment by jjaaxx44** [comment]
Yes I found this issue later, after I sent an email.
So I have added an issue and resolved it on forked branch.
You can find issue in closed section.

**Comment by jjaaxx44** [comment]
FYI there is some internal issue with UIPageViewController caching old view controllers. So I also came to know this later, and as of now there is just one work around the issue, which I have implemented in "abhishek" fork
